apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secret
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpVeE1pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjMU1qUTNPREUzTWl3aWFXRjBJam94TnpVeU5EYzRNVGN5ZlEuLVhQNElmVzVtS2FTeDFxYmtDdmliOFplRzNsZGt1QUhmNjk5ZG5hUzd2czR4azYtWmh6TEVNYTNFVXpuNEJiVndsZ3pzZ29JSy14bXNwNzNaemlyNFE=
  # use this secret file to store sensitive information like JWT tokens, database credentials, etc. in backend-deployment.yml
  # above is an example of a JWT token encoded in base64